"""initial

Revision ID: 6446f8b64674
Revises: 
Create Date: 2026-08-19 15:41:41.289057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('personagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('classe', sa.String(), nullable=False),
    sa.Column('alinhamento', sa.String(), nullable=False),
    sa.Column('background', sa.String(), nullable=False),
    sa.Column('objetivo', sa.String(), nullable=False),
    sa.Column('hp_atual', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('defesa', sa.Integer(), nullable=False),
    sa.Column('atributos', sa.JSON(), nullable=False),
    sa.Column('inventario', sa.JSON(), nullable=False),
    sa.Column('quest_log', sa.JSON(), nullable=False),
    sa.Column('world_state', sa.JSON(), nullable=False),
    sa.Column('combat_state', sa.JSON(), nullable=False),
    sa.Column('historico_chat', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personagens_session_id'), 'personagens', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personagens_session_id'), table_name='personagens')
    op.drop_table('personagens')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
