"""memoria etapa 5

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-19 20:07:21.209190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('eventos_memoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personagem_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('personagens_citados', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_memoria_personagem_id'), 'eventos_memoria', ['personagem_id'], unique=False)
    # server_default='{}' nos dois: sem isso, SQLite recusa um ADD COLUMN
    # NOT NULL numa tabela com linhas existentes (mesmo motivo do
    # server_default='10' da migration 0002, ver ADR-0004).
    op.add_column('personagens', sa.Column('resumo_rolante', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('personagens', sa.Column('turno_resumido_ate', sa.Integer(), server_default='0', nullable=False))
    op.add_column('personagens', sa.Column('reputacao_npcs', sa.JSON(), nullable=False, server_default='{}'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personagens', 'reputacao_npcs')
    op.drop_column('personagens', 'turno_resumido_ate')
    op.drop_column('personagens', 'resumo_rolante')
    op.drop_index(op.f('ix_eventos_memoria_personagem_id'), table_name='eventos_memoria')
    op.drop_table('eventos_memoria')
    # ### end Alembic commands ###
