"""telemetria e feedback etapa 9

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-22 13:16:52.585889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_telemetria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('personagem_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_telemetria_criado_em'), 'eventos_telemetria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_eventos_telemetria_personagem_id'), 'eventos_telemetria', ['personagem_id'], unique=False)
    op.create_index(op.f('ix_eventos_telemetria_usuario_id'), 'eventos_telemetria', ['usuario_id'], unique=False)
    op.create_table('feedback_narracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personagem_id', sa.Integer(), nullable=False),
    sa.Column('turno_index', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_narracoes_personagem_id'), 'feedback_narracoes', ['personagem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_narracoes_personagem_id'), table_name='feedback_narracoes')
    op.drop_table('feedback_narracoes')
    op.drop_index(op.f('ix_eventos_telemetria_usuario_id'), table_name='eventos_telemetria')
    op.drop_index(op.f('ix_eventos_telemetria_personagem_id'), table_name='eventos_telemetria')
    op.drop_index(op.f('ix_eventos_telemetria_criado_em'), table_name='eventos_telemetria')
    op.drop_table('eventos_telemetria')
    # ### end Alembic commands ###
