"""email verificado etapa 10

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-22 17:06:04.526329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` (não só o default do lado do ORM) porque a tabela já
    # tem linhas: sem isso, o ALTER TABLE falha tanto em SQLite quanto em
    # Postgres ("Cannot add a NOT NULL column with default value NULL").
    # Contas que já existiam viram não-verificadas — correto: elas nunca
    # passaram pelo fluxo de confirmação (Etapa 10, A-2).
    op.add_column(
        "usuarios", sa.Column("email_verificado", sa.Boolean(), nullable=False, server_default=sa.false())
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
